### ISSUE TITLE
error occurred in the <ForwardRef> component

### ISSUE THREAD

**Issue by shensven** [PedroBern/react-native-collapsible-tab-view#235]
After installed the `react-native-collapsible-tab-view` and wrote a minimal example, jest does not pass

## The error in the terminal
```sh
yarn run v1.22.15
$ jest
 FAIL  __tests__/App-test.tsx (25.798 s)
  ✕ renders correctly (228 ms)

  ● renders correctly

    TypeError: Cannot read properties of undefined (reading 'toString')

      at reduce (node_modules/react-native-reanimated/lib/reanimated2/hook/utils.js:46:33)
          at Array.reduce (<anonymous>)
      at buildWorkletsHash (node_modules/react-native-reanimated/lib/reanimated2/hook/utils.js:44:36)
      at buildDependencies (node_modules/react-native-reanimated/lib/reanimated2/hook/utils.js:60:27)
      at useHandler (node_modules/react-native-reanimated/lib/reanimated2/hook/utils.js:36:20)
      at useAnimatedScrollHandler (node_modules/react-native-reanimated/lib/reanimated2/hook/useAnimatedScrollHandler.js:5:47)
      at node_modules/react-native-collapsible-tab-view/lib/commonjs/Container.tsx:284:30
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6016:18)
      at updateForwardRef (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8038:20)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10015:16)

  console.warn
    [react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!

      at showRngh2NoticeIfNeeded (node_modules/react-native-gesture-handler/lib/commonjs/handlers/createHandler.ts:128:5)
      at new Handler (node_modules/react-native-gesture-handler/lib/commonjs/handlers/createHandler.ts:176:9)
      at constructClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4022:18)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8399:5)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9990:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)

  console.error
    The above error occurred in the <ForwardRef> component:
    
        at /Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-collapsible-tab-view/lib/commonjs/Container.tsx:63:7
        at Home (/Users/shensven/Documents/GitHub/Readhubn/src/screens/Home.tsx:9:46)
        at StaticContainer (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/core/lib/commonjs/StaticContainer.tsx:7:3)
        at EnsureSingleNavigator (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/core/lib/commonjs/EnsureSingleNavigator.tsx:20:49)
        at SceneView (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/core/lib/commonjs/SceneView.tsx:33:3)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at CardSheet (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardSheet.tsx:15:3)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at AnimatedComponent (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:44:43)
        at AnimatedComponentWrapper
        at Handler (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-gesture-handler/lib/commonjs/handlers/createHandler.ts:163:51)
        at PanGestureHandler (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/GestureHandlerNative.tsx:10:22)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at AnimatedComponent (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:44:43)
        at AnimatedComponentWrapper
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at Card (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/Card.tsx:92:58)
        at CardContainer (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardContainer.tsx:59:24)
        at RNSScreen
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockNativeComponent.js:15:18)
        at AnimatedComponent (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:44:43)
        at AnimatedComponentWrapper
        at MaybeFreeze (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-screens/lib/commonjs/index.native.tsx:169:22)
        at Screen (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-screens/lib/commonjs/index.native.tsx:206:51)
        at MaybeScreen (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Screens.tsx:26:29)
        at RNSScreenContainer
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockNativeComponent.js:15:18)
        at ScreenContainer (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-screens/lib/commonjs/index.native.tsx:324:11)
        at MaybeScreenContainer (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Screens.tsx:12:38)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at Background (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/elements/lib/commonjs/Background.tsx:9:36)
        at CardStack (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardStack.tsx:384:29)
        at RNCSafeAreaProvider
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockNativeComponent.js:15:18)
        at SafeAreaProvider (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-safe-area-context/lib/commonjs/SafeAreaContext.tsx:24:34)
        at SafeAreaProviderCompat (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/elements/lib/commonjs/SafeAreaProviderCompat.tsx:34:48)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at GestureHandlerRootView
        at StackView (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:63:70)
        at StackNavigator (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/navigators/createStackNavigator.tsx:33:25)
        at EnsureSingleNavigator (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/core/lib/commonjs/EnsureSingleNavigator.tsx:20:49)
        at BaseNavigationContainer (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/core/lib/commonjs/BaseNavigationContainer.tsx:81:5)
        at ThemeProvider (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/native/lib/commonjs/theming/ThemeProvider.tsx:11:39)
        at NavigationContainerInner (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/native/lib/commonjs/NavigationContainer.tsx:55:5)
        at App
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10989:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11022:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3662:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3683:9)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11855:11)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        25.891 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## minimal example

```ts
// src/screens/Home.tsx
import React, {useCallback} from 'react';
import {ListRenderItem, StyleSheet, View} from 'react-native';
import {Tabs} from 'react-native-collapsible-tab-view';

const DATA = [0, 1, 2, 3, 4];
const identity = (v: unknown): string => v + '';

const Home: React.FC = () => {
  const renderItem: ListRenderItem<number> = useCallback(({index}) => {
    return <View style={[styles.box, index % 2 === 0 ? styles.boxB : styles.boxA]} />;
  }, []);

  return (
    <Tabs.Container>
      <Tabs.Tab name="A">
        <Tabs.FlatList data={DATA} renderItem={renderItem} keyExtractor={identity} />
      </Tabs.Tab>
      <Tabs.Tab name="B">
        <Tabs.FlatList data={DATA} renderItem={renderItem} keyExtractor={identity} />
      </Tabs.Tab>
    </Tabs.Container>
  );
};

const styles = StyleSheet.create({
  box: {
    height: 250,
    width: '100%',
  },
  boxA: {
    backgroundColor: 'white',
  },
  boxB: {
    backgroundColor: '#D8D8D8',
  },
  header: {
    height: 250,
    width: '100%',
    backgroundColor: '#2196f3',
  },
});

export default Home;
```

## Reference 
https://github.com/shensven/Readhubn/commit/9b0877f890d9acf5542ec91964dc374307270f0c
https://github.com/software-mansion/react-native-reanimated/issues/2994

**Comment by shensven** [comment]
Everything works fine after adding the mock
```js
// jest.setup.js
global.__reanimatedWorkletInit = () => {};

jest.mock('react-native-reanimated', () => {
  const Reanimated = require('react-native-reanimated/mock');
  Reanimated.default.call = () => {};
  return Reanimated;
});
```

**Comment by shail-spreadd** [comment]
@shensven i am still facing this issue 
it is giving me forward ref error 

i have place the code that you gave in jest.setup.js file
